theme: doit

enableRobotsTXT: true
enableEmoji: true

title: JokaJukka
copyright: 2025 Miroslav Jarý

# Languages & multilang content
defaultContentLanguage: cs
languages:
  cs:
    languageName: Česky
    weight: 10
    contentDir: content/cs
    params:
      home:
        profile:
          avatarURL: /images/avatar.jpg
          title: Bc. Miroslav Jarý <br><small>(JokaJukka)</small>
          subtitle: Student & vývojář
          social: true
          typeit: trues
    menu:
      main:
        - weight: 1
          identifier: blog
          pre: <i class='fas fa-user fa-fw'></i>
          name: Blog
          url: /blog/
        - weight: 2
          identifier: projects
          pre: <i class='fas fa-book-open fa-fw'></i>
          name: Projekty
          url: /projects/
  en:
    languageName: English
    contentDir: content/en
    params:
      home:
        profile:
          avatarURL: /images/avatar.jpg
          title: Bc. Miroslav Jarý <br><small>(JokaJukka)</small>
          subtitle: Student & developer
          social: true
          typeit: true
    menu:
      main:
        - weight: 1
          identifier: blog
          pre: <i class='fas fa-user fa-fw'></i>
          name: Blog
          url: /en/blog/
        - weight: 2
          identifier: projects
          pre: <i class='fas fa-book-open fa-fw'></i>
          name: Projects
          url: /en/projects/

# Page author
author:
  name: Miroslav Jarý
  link: "https://jokajukka.github.io"

# Theme params
params:
  # Social networks
  social:
    Linkedin: jokajukka
    Github: jokajukka
    Twitter: jokajukka
    Mastodon: "@jukka@mastodon.arch-linux.cz"
  # Theme properties
  version: "0.4.X"
  dateFormat: 02. 01. 2022
  title: JokaJukka
  description: Student & vývojář
  footer:
    since: 2022
  page:
    # CSS/JS libraries
    library:
      js:
        cardEffect: "js/cardEffect.js"
    # Page comments
    comment:
      enable: true
      giscus:
        enable: true
        # owner/repo
        dataRepo: "JokaJukka/jokajukka.github.io"
        dataRepoId: "R_kgDOIVbmbw"
        dataCategory: "Web comments"
        dataCategoryId: "DIC_kwDOIVbmb84CbPX5"
        dataMapping: "title"
# false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
markup:
  highlight:
    noClasses: false
