theme: doit

enableRobotsTXT: true
enableEmoji: true

title: JokaJukka
copyright: 2022 Miroslav Jarý <mira.jary@gmail.com>

# Languages & multilang content
defaultContentLanguage: cs
languages:
  cs:
    languageName: Česky
    weight: 10
    contentDir: content/cs
    params:
      home:
        profile:
          avatarURL: /images/avatar.jpg
          title: Miroslav Jarý <br><small>(JokaJukka)</small>
          subtitle: Student & vývojář
          social: true
          typeit: trues
    menu:
      main:
        # - weight: 1
        #   identifier: about
        #   pre: <i class='fas fa-user fa-fw'></i>
        #   name: O mně
        #   url: /about/
        - weight: 2
          identifier: projects
          pre: <i class='fas fa-book-open fa-fw'></i>
          name: Projekty
          url: /projects/
        # - weight: 3
        #   identifier: contact
        #   pre: <i class='fas fa-phone fa-fw'></i>
        #   name: Kontakt
        #   url: /contact/
  en:
    languageName: English
    contentDir: content/en
    params:
      home:
        profile:
          avatarURL: /images/avatar.jpg
          title: Miroslav Jarý <br><small>(JokaJukka)</small>
          subtitle: Student & developer
          social: true
          typeit: true
    menu:
      main:
        # - weight: 1
        #   identifier: about
        #   pre: <i class='fas fa-user fa-fw'></i>
        #   name: About me
        #   url: /en/about/
        - weight: 2
          identifier: projects
          pre: <i class='fas fa-book-open fa-fw'></i>
          name: Projects
          url: /en/projects/
        # - weight: 3
        #   identifier: contact
        #   pre: <i class='fas fa-phone fa-fw'></i>
        #   name: Contact
        #   url: /en/contact/

# Page author
author:
  name: Miroslav Jarý
  email: mira.jary@gmail.com
  link: 'https://jokajukka.github.io'

# Theme params
params:
  # Social networks
  social:
    Linkedin: jokajukka
    Github: jokajukka
    Twitter: jokajukka
    Instagram: mira.j.jary
    Facebook: mira.j.jary
    Mastodon: "@jukka@mastodon.arch-linux.cz"
    Email: "mira.jary@gmail.com"
  # Theme properties
  version: "0.2.X"
  dateFormat: 02. 01. 2022
  title: JokaJukka
  description: Student & vývojář
  footer:
    since: 2022
  
  # CSS/JS libraries
  page:
    library:
      js:
        cardEffect: "js/cardEffect.js"

# false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
markup:
  highlight:
    noClasses: false