enableRobotsTXT: true
enableEmoji: true

module:
  imports:
    - path: github.com/hugo-toha/toha/v4

params:
  background: "images/background_light.jpg"
  features:
    darkMode:
      enable: true
  footer:
    newsletter:
      enable: false
# Languages & multilang content
defaultContentLanguage: cs
languages:
  cs:
    languageName: Česky
    weight: 1
  en:
    languageName: English
    weight: 2
