baseurl = "http://jukka.local:1313"

theme = "loveit"
paginate = 10
copyright = "2022 Miroslav Jarý <mira.jary@gmail.com>"


enableRobotsTXT = true
enableEmoji = true


defaultContentLanguage = "cs"
[languages]
  [languages.cs]
    languageName = "Česky"
    weight = 10
    contentDir = "content/cs"
    [languages.cs.params.home.profile]
      avatarURL = "/images/avatar.jpg"
      title = "Miroslav Jarý <br><small>(JokaJukka)</small>"
      subtitle = "Student & vývojář"
      social = true
      typeit = true
  [languages.cs.menu]
    [[languages.cs.menu.main]]
      weight = 1
      identifier = "about"
      pre = "<i class='fas fa-user fa-fw'></i>"
      name = "O mně"
      url = "/about/"
    [[languages.cs.menu.main]]
      weight = 2
      identifier = "projects"
      pre = "<i class='fas fa-book-open fa-fw'></i>"
      name = "Projekty"
      url = "/projects/"
    [[languages.cs.menu.main]]
      weight = 3
      identifier = "contact"
      pre = "<i class='fas fa-phone fa-fw'></i>"
      name = "Kontakt"
      url = "/contact/"
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    [languages.en.params.home.profile]
      avatarURL = "/images/avatar.jpg"
      title = "Miroslav Jarý <br><small>(JokaJukka)</small>"
      subtitle = "Student & developer"
      social = true
      typeit = true
  [languages.en.menu]
    [[languages.en.menu.main]]
      weight = 1
      identifier = "about"
      pre = "<i class='fas fa-user fa-fw'></i>"
      name = "About me"
      url = "/en/about/"
    [[languages.en.menu.main]]
      weight = 2
      identifier = "projects"
      pre = "<i class='fas fa-book-open fa-fw'></i>"
      name = "Projects"
      url = "/en/projects/"
    [[languages.en.menu.main]]
      weight = 3
      identifier = "contact"
      pre = "<i class='fas fa-phone fa-fw'></i>"
      name = "Contact"
      url = "/en/contact/"

[params.social]
  Linkedin = "jokajukka"
  Github = "jokajukka"
  Twitter = "jokajukka"
  Instagram = "mira.j.jary"
  Facebook = "mira.j.jary"

[params]
  version = "0.2.X"
  defaultTheme = "auto"
  dateFormat = "02. 01. 2022"
  
  title = "JokaJukka"
  description = "Student & vývojář"

  # Header config
  [params.header]
    [params.header.title]
      name = "JokaJukka"

  # Footer config
  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = 2022
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (all posts) page config
  [params.section]
    paginate = 10
    dateFormat = "02. 01"

  # List (category or tag) page config
  [params.list]
    paginate = 10
    dateFormat = "02. 01"

  # App icon config
  [params.app]
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
    # Home page posts
    [params.home.posts]
      enable = false



[author]
  name = "Miroslav Jarý"
  email = "mira.jary@gmail.com"
  link = "https://jokajukka.github.io"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
